### ISSUE TITLE
TED Express dataset

### ISSUE THREAD

**Issue by hykim0** [alvinliu0/HA2G#2]
Are you going to release the TED Express dataset?
It will be helpful for further research.

**Comment by alvinliu0** [comment]
Hi :)

Many thanks for your interest to our work! Since we authors are currently busy with some project deadlines, we will release the code and data later. About the data, I will try my best to apply for the public release of original data since this work is done during my internship. Even if this is not permitted, I will still make the dataset building script publicly available to help further research in this community. Stay tuned!

Best,
Alvin

**Comment by alvinliu0** [comment]
Hi @hykim0 :)

The pre-processed TED Expressive dataset as well as its accompanied dataset establishment scripts are updated.

Best,
Alvin

**Comment by chikiuso** [comment]
Hi @alvinliu0 

  I just try to download the datasets but it seems they don't work, may I have you to have a look? thanks!
